"""Add new column to Grade

Revision ID: 7a2d90cc58d5
Revises: 
Create Date: 2025-09-12 17:34:01.030578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2d90cc58d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('companies', 'updated_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('employees', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('marital_status', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('blood_group', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('category', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('religion', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('nationality', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('adhaar_number', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('pan_number', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('passport_number', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('esic_number', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('uan_number', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('pf_number', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('is_disability', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('disability_type', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('disability_certificate_file', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('current_address', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('current_postal_code', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('current_city', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('current_state', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('current_country', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('permanent_postal_code', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('permanent_address', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('permanent_city', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('permanent_state', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('permanent_country', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('emergency_contact_name', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('emergency_contact_relationship', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('emergency_contact_phone', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('employee_code', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('official_email', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('rejoin_date', sa.DateTime(), nullable=True))
    op.add_column('employees', sa.Column('date_of_leaving', sa.DateTime(), nullable=True))
    op.add_column('employees', sa.Column('reason_of_leaving', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('relieving_certificate_file', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('probation_period_months', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('confirmation_date', sa.DateTime(), nullable=True))
    op.add_column('employees', sa.Column('notice_period_days', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_employees_adhaar_number'), 'employees', ['adhaar_number'], unique=True)
    op.create_index(op.f('ix_employees_esic_number'), 'employees', ['esic_number'], unique=True)
    op.create_index(op.f('ix_employees_official_email'), 'employees', ['official_email'], unique=True)
    op.create_index(op.f('ix_employees_pan_number'), 'employees', ['pan_number'], unique=True)
    op.create_index(op.f('ix_employees_passport_number'), 'employees', ['passport_number'], unique=True)
    op.create_index(op.f('ix_employees_pf_number'), 'employees', ['pf_number'], unique=True)
    op.create_index(op.f('ix_employees_uan_number'), 'employees', ['uan_number'], unique=True)
    op.drop_column('employees', 'address')
    op.drop_column('employees', 'emp_code')
    op.add_column('grades', sa.Column('min_salary', sa.Float(), nullable=True))
    op.add_column('grades', sa.Column('max_salary', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'max_salary')
    op.drop_column('grades', 'min_salary')
    op.add_column('employees', sa.Column('emp_code', sa.VARCHAR(), nullable=True))
    op.add_column('employees', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_employees_uan_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_pf_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_passport_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_pan_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_official_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_esic_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_adhaar_number'), table_name='employees')
    op.drop_column('employees', 'notice_period_days')
    op.drop_column('employees', 'confirmation_date')
    op.drop_column('employees', 'probation_period_months')
    op.drop_column('employees', 'relieving_certificate_file')
    op.drop_column('employees', 'reason_of_leaving')
    op.drop_column('employees', 'date_of_leaving')
    op.drop_column('employees', 'rejoin_date')
    op.drop_column('employees', 'official_email')
    op.drop_column('employees', 'employee_code')
    op.drop_column('employees', 'emergency_contact_phone')
    op.drop_column('employees', 'emergency_contact_relationship')
    op.drop_column('employees', 'emergency_contact_name')
    op.drop_column('employees', 'permanent_country')
    op.drop_column('employees', 'permanent_state')
    op.drop_column('employees', 'permanent_city')
    op.drop_column('employees', 'permanent_address')
    op.drop_column('employees', 'permanent_postal_code')
    op.drop_column('employees', 'current_country')
    op.drop_column('employees', 'current_state')
    op.drop_column('employees', 'current_city')
    op.drop_column('employees', 'current_postal_code')
    op.drop_column('employees', 'current_address')
    op.drop_column('employees', 'disability_certificate_file')
    op.drop_column('employees', 'disability_type')
    op.drop_column('employees', 'is_disability')
    op.drop_column('employees', 'pf_number')
    op.drop_column('employees', 'uan_number')
    op.drop_column('employees', 'esic_number')
    op.drop_column('employees', 'passport_number')
    op.drop_column('employees', 'pan_number')
    op.drop_column('employees', 'adhaar_number')
    op.drop_column('employees', 'nationality')
    op.drop_column('employees', 'religion')
    op.drop_column('employees', 'category')
    op.drop_column('employees', 'blood_group')
    op.drop_column('employees', 'marital_status')
    op.drop_column('employees', 'gender')
    op.drop_column('employees', 'age')
    op.drop_column('employees', 'profile_picture')
    op.alter_column('companies', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('companies', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
